# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2adee1cd244a0aaf0ae45be8f4efac30"
name = "albisleasingapp"
handle = "albisleasingapp"
application_url = "https://vi-verizon-nh-dynamics.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "helge-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://vi-verizon-nh-dynamics.trycloudflare.com/auth/callback",
  "https://vi-verizon-nh-dynamics.trycloudflare.com/auth/shopify/callback",
  "https://vi-verizon-nh-dynamics.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
