# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2ff7d621bb5b99a479b6ffa32b6c08c5"
name = "CP - Albis Leasing"
handle = "albis-leasing-1"
application_url = "https://provision-prayer-nc-egyptian.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "helge-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://provision-prayer-nc-egyptian.trycloudflare.com/auth/callback",
  "https://provision-prayer-nc-egyptian.trycloudflare.com/auth/shopify/callback",
  "https://provision-prayer-nc-egyptian.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
